polls/urls.py
from django.urls import path
from . import views

app_name='polls'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'), 
    path("<int:pk>/", views.DetailView.as_view(), name='details'), 
    path("<int:pk>/results/", views.ResultsView.as_view(), name='results'),
    path("<int:question_id>/vote/", views.vote, name='vote')]

website/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'Anket yönetim'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/' , include("polls.urls"), name='Anketler')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.contrib import admin

class Questions(models.Model):
    question_text = models.CharField("Soru metni", max_length=200)
    pub_date = models.DateTimeField("Yayın tarihi")

    def __str__(self) -> str:
        return self.question_text
    
    @admin.display(
            boolean=True,
            ordering=pub_date,
            description='Yeni mi yayınlandı')
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

    class Meta:
        verbose_name = 'Soru'
        verbose_name_plural = 'Sorular'


class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self) -> str:
        return self.choice_text

    class Meta:
        verbose_name = 'Seçenek'
        verbose_name_plural = 'Seçenekler'

polls/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Questions, Choice

# Generic views
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_questions_list"

    def get_queryset(self):
        return Questions.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Questions
    template_name = "polls/details.html"

    def get_queryset(self):
        """
        Henüz yayınlanmamış `Questions`ları dahil etmez.
        """
        return Questions.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Questions
    template_name = "polls/results.html"


def index(request):
    latest_question_list = Questions.objects.order_by("-pub_date")[:5]
    return render(request, 'polls/index.html', {'latest_questions_list': latest_question_list})

def details(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    if request.method == "POST":
        question = get_object_or_404(Questions, pk=question_id)

        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question':question,
                'error_message': 'You didn\'t select a choice.'
            })
        
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question_id, )))
    else:
        return HttpResponse("<h1>Method Not Allowed</h1>", status=405)

polls/templates/polls/details.html
{% extends 'polls/template.html' %}
{% block title %}Sorular{% endblock %}
{% block content %}
    <form action="{% url 'polls:vote' questions.id %}" method="post" class="form-check">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ questions.question_text }}</h1></legend>
            {% if error_message %}
                <div class="alert alert-danger">{{ error_message }}</div>
            {% endif %}
            {% for choice in questions.choice_set.all %}
                <input type="radio" class="form-check-input" name="choice" id="choice{{ forloop.counter }}" value={{choice.id}}>
                <label for="choice{{ forloop.counter }}" class="form-check-label">{{ choice.choice_text }}</label>
                <br>
            {% endfor %}
        </fieldset>
        <input class="form-control" type="submit" value="Vote">

    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/template.html' %}
{% block title %}Sorular{% endblock %}
{% block content %}
    {% if latest_questions_list %}
        <ul>

        {% for question in latest_questions_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
        
        </ul>
    {% else %}
    <p>Soru bulunamadı!</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/template.html' %}
{% block title %}Sonuçlar{% endblock %}
{% block content %}
<div class="card" style="width: 18rem;">
    <h1>{{ question.question_text }}</h1>

    <ul class="text-center">
    {% for choice in questions.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} Oy</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:details' questions.id %}" class="btn btn-primary">Tekrar oyla?</a>
</div>
{% endblock %}

polls/templates/polls/template.html
<!DOCTYPE html>
<html lang="tr" data-bs-theme='dark'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="{% static 'polls/style/bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <container>
        <button><a href="{% url "polls:index" %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
            </svg>
        </a></button>
        <div class="position-absolute top-50 start-50 translate-middle">    

            {% block content %}
            {% endblock %}
        
        </div>

    </container>
    <style>
        a{
            text-decoration: None;
            color:dark-blue;
        }
        button{
            margin: 2rem;
            padding: auto, 0;
            border-radius: 20%;
            border-decoration: solid;
        }
    </style>

    <script src="{% static 'polls/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>